namespace DataHubIntern.MinimumApi.ApiClient.Models;

public record RichInfoResponse(string Soc, string MainIndustrialClassName, int LatestSalesAccountingTermSalesGreaterThan, int LatestSalesAccountingTermSalesLessThan);